/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tb1_proyecto;

import com.opencsv.exceptions.CsvException;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hriverav dependencias: opencsv msqlconnector/j Apache Commons Lang 3
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setResizable(false); // Desactiva la redimensionabilidad
        setLocationRelativeTo(null);
        try {
            BD.conexion();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_CRUD = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton_CRUD_Create = new javax.swing.JButton();
        jButton_CRUD_Read = new javax.swing.JButton();
        jButton_CRUD_Update = new javax.swing.JButton();
        jButton_CRUD_Delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlListaTablas = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jdCreate = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Create = new javax.swing.JTable();
        jdGuardarCreate = new javax.swing.JButton();
        jdCreate_Return = new javax.swing.JButton();
        jdUpdate = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtUpdateTable = new javax.swing.JTable();
        jdGuardarUpdate = new javax.swing.JButton();
        jButton_Update_Regresar = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_Update_BuscarPk = new javax.swing.JTextField();
        jButton_Update_Buscar = new javax.swing.JButton();
        jdRead = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jdGuardarUpdate1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField_read = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jdReadTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jdDelete = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tfPKbusqueda = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();
        jPanel_Principal = new javax.swing.JPanel();
        jButton_Principal_SubirArchivo = new javax.swing.JButton();
        jLabel_Principal_Route = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_Principal_AbrirOptions = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_loaded_files = new javax.swing.JList<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton_CRUD_Create.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_CRUD_Create.setText("Create");
        jButton_CRUD_Create.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_CRUD_Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CRUD_CreateMouseClicked(evt);
            }
        });
        jButton_CRUD_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CRUD_CreateActionPerformed(evt);
            }
        });

        jButton_CRUD_Read.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_CRUD_Read.setText("Read");
        jButton_CRUD_Read.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_CRUD_Read.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CRUD_ReadMouseClicked(evt);
            }
        });
        jButton_CRUD_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CRUD_ReadActionPerformed(evt);
            }
        });

        jButton_CRUD_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_CRUD_Update.setText("Update");
        jButton_CRUD_Update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_CRUD_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CRUD_UpdateMouseClicked(evt);
            }
        });
        jButton_CRUD_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CRUD_UpdateActionPerformed(evt);
            }
        });

        jButton_CRUD_Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_CRUD_Delete.setText("Delete");
        jButton_CRUD_Delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_CRUD_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CRUD_DeleteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("       C  R  U  D");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jlListaTablas.setBorder(null);
        jlListaTablas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlListaTablas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "categoria", "proveedor", "producto", "inventario", "clientes", "empleados", "rutas", "pedidos", "detalles_pedidos", "pagos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlListaTablas.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jlListaTablas.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jlListaTablas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jlListaTablas);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TABLAS DISPONIBLES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_CRUD_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_CRUD_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_CRUD_Read, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_CRUD_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CRUD_Create, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_CRUD_Read, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CRUD_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_CRUD_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_CRUDLayout = new javax.swing.GroupLayout(jDialog_CRUD.getContentPane());
        jDialog_CRUD.getContentPane().setLayout(jDialog_CRUDLayout);
        jDialog_CRUDLayout.setHorizontalGroup(
            jDialog_CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_CRUDLayout.setVerticalGroup(
            jDialog_CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CREATE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTable_Create.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Create.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable_Create);

        jdGuardarCreate.setText("GUARDAR");
        jdGuardarCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdGuardarCreateMouseClicked(evt);
            }
        });
        jdGuardarCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdGuardarCreateActionPerformed(evt);
            }
        });

        jdCreate_Return.setText("RETURN");
        jdCreate_Return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdCreate_ReturnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jdCreate_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdGuardarCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdCreate_Return, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdGuardarCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdCreateLayout = new javax.swing.GroupLayout(jdCreate.getContentPane());
        jdCreate.getContentPane().setLayout(jdCreateLayout);
        jdCreateLayout.setHorizontalGroup(
            jdCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCreateLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdCreateLayout.setVerticalGroup(
            jdCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UPDATE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtUpdateTable.setModel(new DefaultTableModel());
        jScrollPane4.setViewportView(jtUpdateTable);

        jdGuardarUpdate.setText("GUARDAR");
        jdGuardarUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdGuardarUpdateActionPerformed(evt);
            }
        });

        jButton_Update_Regresar.setText("REGRESAR");
        jButton_Update_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Update_RegresarActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Primary Key:");

        jTextField_Update_BuscarPk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Update_BuscarPkActionPerformed(evt);
            }
        });

        jButton_Update_Buscar.setText("Search");
        jButton_Update_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Update_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jButton_Update_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Update_BuscarPk)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Update_BuscarPk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton_Update_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton_Update_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(jdGuardarUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Update_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdGuardarUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdUpdateLayout = new javax.swing.GroupLayout(jdUpdate.getContentPane());
        jdUpdate.getContentPane().setLayout(jdUpdateLayout);
        jdUpdateLayout.setHorizontalGroup(
            jdUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdUpdateLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdUpdateLayout.setVerticalGroup(
            jdUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("READ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jdGuardarUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jdGuardarUpdate1.setText("SEARCH");
        jdGuardarUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdGuardarUpdate1MouseClicked(evt);
            }
        });
        jdGuardarUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdGuardarUpdate1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("PRIMARY KEY");

        jdReadTable.setModel(new DefaultTableModel());
        jScrollPane5.setViewportView(jdReadTable);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("RESULTADO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jdGuardarUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jTextField_read, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_read, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jdGuardarUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdReadLayout = new javax.swing.GroupLayout(jdRead.getContentPane());
        jdRead.getContentPane().setLayout(jdReadLayout);
        jdReadLayout.setHorizontalGroup(
            jdReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdReadLayout.setVerticalGroup(
            jdReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DELETE");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jbBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbBuscar.setText("SEARCH");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("PRIMARY KEY");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("RESULTADO");

        jbEliminar.setText("ELIMINAR");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPKbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 346, Short.MAX_VALUE)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPKbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdDeleteLayout = new javax.swing.GroupLayout(jdDelete.getContentPane());
        jdDelete.getContentPane().setLayout(jdDeleteLayout);
        jdDeleteLayout.setHorizontalGroup(
            jdDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdDeleteLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jdDeleteLayout.setVerticalGroup(
            jdDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Principal.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Principal.setForeground(new java.awt.Color(255, 255, 255));

        jButton_Principal_SubirArchivo.setText("Subir Archivo");
        jButton_Principal_SubirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Principal_SubirArchivoActionPerformed(evt);
            }
        });

        jLabel_Principal_Route.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cvsimage.png"))); // NOI18N

        jButton_Principal_AbrirOptions.setText("Abrir");
        jButton_Principal_AbrirOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Principal_AbrirOptionsMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Desea realizar operaciones CRUD?");

        jList_loaded_files.setModel(new DefaultListModel<>());
        jList_loaded_files.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList_loaded_files);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del CSV:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));

        jLabel14.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DATABASE");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel_PrincipalLayout = new javax.swing.GroupLayout(jPanel_Principal);
        jPanel_Principal.setLayout(jPanel_PrincipalLayout);
        jPanel_PrincipalLayout.setHorizontalGroup(
            jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                                .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(156, 156, 156)
                                .addComponent(jLabel2)
                                .addGap(101, 101, 101)
                                .addComponent(jLabel_Principal_Route, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_Principal_SubirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Principal_AbrirOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_PrincipalLayout.setVerticalGroup(
            jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PrincipalLayout.createSequentialGroup()
                .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_PrincipalLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel_Principal_Route, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton_Principal_SubirArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Principal_AbrirOptions)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Principal_SubirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Principal_SubirArchivoActionPerformed
        //Filechooser
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV", "csv", "CSV");
        fc.setFileFilter(filter);

        int res = fc.showOpenDialog(this);
        if (res != JFileChooser.CANCEL_OPTION) {
            File name = fc.getSelectedFile();

            if ((name == null) || name.getName().equals("")) {
                JOptionPane.showMessageDialog(this, "Error al abrir el archivo");
            } else {
                DefaultListModel<String> model = (DefaultListModel) jList_loaded_files.getModel();
                boolean notfound = true;
                for (Object object : model.toArray()) {
                    if (object.toString().equals(name.getName())) {
                        notfound = false;
                    }
                }
                if (notfound) {
                    model.addElement(name.getName());
                    jList_loaded_files.setModel(model);
                    new FileManager(name).ReadFile(BD);
                } else {
                    JOptionPane.showMessageDialog(null, "Error, no puede subir el mismo archivo 2 veces");
                }
            }
        }
    }//GEN-LAST:event_jButton_Principal_SubirArchivoActionPerformed

    private void jButton_Principal_AbrirOptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Principal_AbrirOptionsMouseClicked
        //CRUD options
        jDialog_CRUD.pack();
        jDialog_CRUD.setLocationRelativeTo(this);
        jDialog_CRUD.setModal(true);
        jDialog_CRUD.setVisible(true);
    }//GEN-LAST:event_jButton_Principal_AbrirOptionsMouseClicked

    private void jButton_CRUD_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CRUD_ReadActionPerformed
        //read buttom

    }//GEN-LAST:event_jButton_CRUD_ReadActionPerformed

    private void jButton_CRUD_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CRUD_CreateActionPerformed
        //create buttom
        // TODO add your handling code here:

        if (jlListaTablas.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(jDialog_CRUD, "Primero seleccione una tabla");
            return;
        }
        String tabla = jlListaTablas.getSelectedValue();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(attributos(tabla));
        model.addRow(new Object[]{});
        jTable_Create.setModel(model);

        jdCreate.pack();
        jdCreate.setLocationRelativeTo(this);
        jdCreate.setModal(true);
        jdCreate.setVisible(true);

    }//GEN-LAST:event_jButton_CRUD_CreateActionPerformed

    private void jButton_CRUD_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CRUD_UpdateActionPerformed
        //update buttom
        if (jlListaTablas.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(jDialog_CRUD, "Primero seleccione una tabla");
            return;
        }

        String tabla = jlListaTablas.getSelectedValue();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(attributos(tabla));
        jtUpdateTable.setModel(model);
        
        jdUpdate.pack();
        jdUpdate.setLocationRelativeTo(this);
        jdUpdate.setModal(true);
        jdUpdate.setVisible(true);
        
    }//GEN-LAST:event_jButton_CRUD_UpdateActionPerformed

    private void jButton_CRUD_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CRUD_DeleteActionPerformed
        //delete buttom
        if (jlListaTablas.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(jDialog_CRUD, "Primero seleccione una tabla");
            return;
        }
        String tablaNombre = jlListaTablas.getSelectedValue();
        jdDelete.pack();
        jdDelete.setLocationRelativeTo(this);
        jdDelete.setModal(true);
        jdDelete.setVisible(true);
    }//GEN-LAST:event_jButton_CRUD_DeleteActionPerformed

    private void jdGuardarUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdGuardarUpdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdGuardarUpdate1ActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        String tablaNombre = jlListaTablas.getSelectedValue();
        boolean bandera = true;
        if (tfPKbusqueda.getText().equals("")) {
            JOptionPane.showMessageDialog(jdDelete, "Ingrese la llave primaria del elemento a eliminar");
        } else {
            String valorPK = tfPKbusqueda.getText();
            claveElemento = valorPK;
            try {
                bandera = BD.mostrarTupla(tablaNombre, valorPK);
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (bandera) {
                JOptionPane.showMessageDialog(jdDelete, "Elemento encontrado con exito");
                banderaEncontrar = true;
            } else {
                JOptionPane.showMessageDialog(jdDelete, "Elemento no encontrado");
                banderaEncontrar = false;
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jButton_CRUD_CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CRUD_CreateMouseClicked
        // TODO add your handling code here:

        if (jlListaTablas.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(jDialog_CRUD, "Primero seleccione una tabla");
            return;
        }
        String tabla = jlListaTablas.getSelectedValue();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(attributos(tabla));
        model.addRow(new Object[]{});
        jTable_Create.setModel(model);

        jdCreate.pack();
        jdCreate.setLocationRelativeTo(this);
        jdCreate.setModal(true);
        jdCreate.setVisible(true);
    }//GEN-LAST:event_jButton_CRUD_CreateMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jDialog_CRUD.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jdCreate_ReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdCreate_ReturnMouseClicked
        // TODO add your handling code here:

        jdCreate.setModal(false);
        jdCreate.setVisible(false);
        jDialog_CRUD.setVisible(true);
    }//GEN-LAST:event_jdCreate_ReturnMouseClicked

    private void jdGuardarCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdGuardarCreateMouseClicked
        // TODO add your handling code here:
        if (jTable_Create.isEditing()) {
            jTable_Create.getCellEditor().stopCellEditing();
        }

        Object[] rowData = new Object[jTable_Create.getColumnCount()];

        for (int col = 0; col < rowData.length; col++) {
            rowData[col] = jTable_Create.getValueAt(0, col);  // Store the value of each column in the array
        }
        if (validateDataTypes(jlListaTablas.getSelectedValue(), rowData)) {
            try {
                BD.insertarTabla(jlListaTablas.getSelectedValue(), rowData);
                JOptionPane.showMessageDialog(this, "Registro insertado correctamente en " + jlListaTablas.getSelectedValue());
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jdGuardarCreateMouseClicked

    private void jdGuardarCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdGuardarCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdGuardarCreateActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        String tablaNombre = jlListaTablas.getSelectedValue();
        int pk = Integer.parseInt(claveElemento);
        if (banderaEncontrar) {
            try {
                BD.deleteTabla(tablaNombre, pk);
                JOptionPane.showMessageDialog(jdDelete, "Elemento eliminado");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(jdDelete, "Elemento no eliminado");
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        banderaEncontrar = false;
        claveElemento = "";
        tfPKbusqueda.setText("");
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jButton_CRUD_ReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CRUD_ReadMouseClicked
        // TODO add your handling code here:
        if (jlListaTablas.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(jDialog_CRUD, "Primero seleccione una tabla");
            return;
        }
        String tabla = jlListaTablas.getSelectedValue();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(attributos(tabla));
        jdReadTable.setModel(model);

        jdRead.pack();
        jdRead.setLocationRelativeTo(this);
        jdRead.setModal(true);
        jdRead.setVisible(true);

    }//GEN-LAST:event_jButton_CRUD_ReadMouseClicked

    private void jdGuardarUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdGuardarUpdate1MouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel)jdReadTable.getModel();
            model.setRowCount(0);
            if (jTextField_read.getText().trim().equals("*")) {
                Object[][] tuplas = BD.tuplas_select_cinco(jlListaTablas.getSelectedValue());
                for (Object[] tupla : tuplas) {
                    model.addRow(tupla); 
                }
            }
            if (jTextField_read.getText().trim().matches("^[+-]?\\d+$")) {
                Object[] tupla = BD.conseguir_tupla(jlListaTablas.getSelectedValue(), jTextField_read.getText().trim());
                model.addRow(tupla);           
            }
            jdReadTable.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jdGuardarUpdate1MouseClicked

    private void jdGuardarUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdGuardarUpdateActionPerformed
        //guardar cambios de las cosas a cambiar
        if (!banderaEncontrar) {
            JOptionPane.showMessageDialog(jdUpdate, "Debe buscar un registro antes de modificarlo");
            return;
        }

        // Detener edición en la tabla
        if (jtUpdateTable.isEditing()) {
            jtUpdateTable.getCellEditor().stopCellEditing();
        }

        // Obtener datos editados
        Object[] rowData = new Object[jtUpdateTable.getColumnCount()];
        for (int col = 0; col < rowData.length; col++) {
            rowData[col] = jtUpdateTable.getValueAt(0, col);
        }

        int pk = Integer.parseInt(claveElemento);
        try {
            BD.updateTabla(jlListaTablas.getSelectedValue(), pk, rowData);
            JOptionPane.showMessageDialog(jdUpdate, "Registro actualizado correctamente");
            jdUpdate.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jdGuardarUpdateActionPerformed

    private void jButton_CRUD_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CRUD_UpdateMouseClicked
        // TODO add your handling code here:
        if (jlListaTablas.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(jDialog_CRUD, "Primero seleccione una tabla");
            return;
        }
        
        String tabla = jlListaTablas.getSelectedValue();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(attributos(tabla));
        jtUpdateTable.setModel(model);

        jdUpdate.pack();
        jdUpdate.setLocationRelativeTo(this);
        jdUpdate.setModal(true);
        jdUpdate.setVisible(true);
    }//GEN-LAST:event_jButton_CRUD_UpdateMouseClicked

    private void jButton_Update_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Update_RegresarActionPerformed
        //return update
        jdUpdate.setVisible(false);
    }//GEN-LAST:event_jButton_Update_RegresarActionPerformed

    private void jTextField_Update_BuscarPkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Update_BuscarPkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Update_BuscarPkActionPerformed

    private void jButton_Update_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Update_BuscarActionPerformed
        // TODO add your handling code here:
        //primera parte
        String tablaNombre = jlListaTablas.getSelectedValue();
        String valorPK = jTextField_Update_BuscarPk.getText().trim();

        if (valorPK.equals("")) {
            JOptionPane.showMessageDialog(jdUpdate, "Ingrese la llave primaria del registro a modificar");
            return;
        }

        try {
            Object[] tupla = BD.conseguir_tupla(tablaNombre, valorPK);
            if (tupla != null) {
                DefaultTableModel model = (DefaultTableModel) jtUpdateTable.getModel();
                model.setRowCount(0);
                model.addRow(tupla);
                banderaEncontrar = true;
            } else {
                JOptionPane.showMessageDialog(jdUpdate, "Registro no encontrado");
                banderaEncontrar = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_Update_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_CRUD_Create;
    private javax.swing.JButton jButton_CRUD_Delete;
    private javax.swing.JButton jButton_CRUD_Read;
    private javax.swing.JButton jButton_CRUD_Update;
    private javax.swing.JButton jButton_Principal_AbrirOptions;
    private javax.swing.JButton jButton_Principal_SubirArchivo;
    private javax.swing.JButton jButton_Update_Buscar;
    private javax.swing.JButton jButton_Update_Regresar;
    private javax.swing.JDialog jDialog_CRUD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Principal_Route;
    private javax.swing.JList<String> jList_loaded_files;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Principal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable_Create;
    private javax.swing.JTextField jTextField_Update_BuscarPk;
    private javax.swing.JTextField jTextField_read;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JDialog jdCreate;
    private javax.swing.JButton jdCreate_Return;
    private javax.swing.JDialog jdDelete;
    private javax.swing.JButton jdGuardarCreate;
    private javax.swing.JButton jdGuardarUpdate;
    private javax.swing.JButton jdGuardarUpdate1;
    private javax.swing.JDialog jdRead;
    private javax.swing.JTable jdReadTable;
    private javax.swing.JDialog jdUpdate;
    private javax.swing.JList<String> jlListaTablas;
    private javax.swing.JTable jtUpdateTable;
    private javax.swing.JTextField tfPKbusqueda;
    // End of variables declaration//GEN-END:variables
    BaseDeDatos BD = new BaseDeDatos();
    boolean banderaEncontrar = true;
    String claveElemento = "";

    public Object[] attributos(String table) {
        if (table.isBlank()) {
            return new Object[]{};
        }
        if (table == null) {
            return new Object[]{};
        }
        return switch (table.toLowerCase()) {
            case "categoria" ->
                new Object[]{"id_categoria", "nombre", "descripcion"};
            case "proveedor" ->
                new Object[]{"id_proveedor", "nombre", "pais_origen", "contacto_nombre", "contacto_email", "contacto_telefono", "direccion", "tiempo_entrega_promedio"};
            case "producto" ->
                new Object[]{"id_producto", "codigo_barras", "nombre", "descripcion", "id_categoria", "id_proveedor", "precio_compra", "precio_venta_sugerido", "peso_gramos", "dimensiones", "fecha_introduccion"};
            case "inventario" ->
                new Object[]{"id_inventario", "id_producto", "cantidad_disponible", "ubicacion_almacen", "lote", "fecha_ingreso", "fecha_caducidad"};
            case "clientes" ->
                new Object[]{"id_cliente", "nombre_tienda", "tipo_tienda", "propietario", "email", "telefono", "direccion", "ciudad", "codigo_postal", "fecha_registro", "limite_credito", "condiciones_pago"};
            case "empleados" ->
                new Object[]{"id_empleado", "nombre", "apellido", "puesto", "email", "telefono", "fecha_contratacion"};
            case "rutas" ->
                new Object[]{"id_ruta", "nombre", "zona_geografica", "id_empleado_responsable", "dia_semana"};
            case "pedidos" ->
                new Object[]{"id_pedido", "id_cliente", "fecha_pedido", "fecha_entrega_programada", "fecha_entrega_real", "id_empleado_vendedor", "id_ruta", "estado", "notas", "total"};
            case "detalles_pedidos" ->
                new Object[]{"id_detalle", "id_pedido", "id_producto", "cantidad", "precio_unitario", "descuento", "subtotal"};
            case "pagos" ->
                new Object[]{"id_pago", "id_pedido", "fecha_pago", "monto", "metodo_pago", "referencia", "estado"};
            default ->
                new Object[0];
        };
    }

    public boolean validateDataTypes(String tableName, Object[] data) {
        if (tableName == null || data == null) {
            return false;
        }
        int count = 0;
        try {
            switch (tableName.toLowerCase()) {
                case "categoria":
                    if (data.length != 3) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1] instanceof String && data[1].toString().length() < 26) {
                            count++;
                            if (data[2] instanceof String && data[2].toString().length() < 101) {
                                return true;
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                case "proveedor":
                    if (data.length != 8) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1] instanceof String && data[1].toString().length() < 26) {
                            count++;
                            if (data[2] instanceof String && data[2].toString().length() < 41) {
                                count++;
                                if (data[3] instanceof String && data[3].toString().length() < 26) {
                                    count++;
                                    if (data[4] instanceof String && data[4].toString().length() < 71) {
                                        count++;
                                        if (data[5] instanceof String && data[5].toString().length() < 26) {
                                            count++;
                                            if (data[6] instanceof String && data[6].toString().length() < 71) {
                                                count++;
                                                if (data[7].toString().matches("^[+-]?\\d+$")) {
                                                    return true;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                case "producto":
                    if (data.length != 11) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1] instanceof String && data[1].toString().length() < 11) {
                            count++;
                            if (data[2] instanceof String && data[2].toString().length() < 26) {
                                count++;
                                if (data[3] instanceof String && data[3].toString().length() < 101) {
                                    count++;
                                    if (data[4].toString().matches("^[+-]?\\d+$")) {
                                        count++;
                                        if (data[5].toString().matches("^[+-]?\\d+$")) {
                                            count++;
                                            if (data[6].toString().matches("^[+-]?\\d+(\\.\\d+)?$")) {
                                                count++;
                                                if (data[7].toString().matches("^[+-]?\\d+(\\.\\d+)?$")) {
                                                    count++;
                                                    if (data[8].toString().matches("^[+-]?\\d+(\\.\\d+)?$")) {
                                                        count++;
                                                        if (data[9] instanceof String && data[9].toString().length() < 31) {
                                                            count++;
                                                            if (data[10].toString().matches("^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
                                                                return true;
                                                            } else {
                                                                JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido\n Formato: YYYY-MM-DD");
                                                                return false;
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                case "inventario":
                    if (data.length != 7) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1].toString().matches("^[+-]?\\d+$")) {
                            count++;
                            if (data[2].toString().matches("^[+-]?\\d+$")) {
                                count++;
                                if (data[3] instanceof String && data[3].toString().length() < 11) {
                                    count++;
                                    if (data[4] instanceof String && data[4].toString().length() < 16) {
                                        count++;
                                        if (data[5].toString().matches("^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
                                            count++;
                                            if (data[6].toString().matches("^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
                                                return true;
                                            } else {
                                                JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido\n Formato: YYYY-MM-DD");
                                                return false;
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido\n Formato: YYYY-MM-DD");
                                            return false;
                                        }
                                    }
                                }
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                case "clientes":
                    if (data.length != 12) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1] instanceof String && data[1].toString().length() < 51) {
                            count++;
                            if (data[2] instanceof String && data[2].toString().length() < 26) {
                                count++;
                                if (data[3] instanceof String && data[3].toString().length() < 26) {
                                    count++;
                                    if (data[4] instanceof String && data[4].toString().length() < 71) {
                                        count++;
                                        if (data[5] instanceof String && data[5].toString().length() < 26) {
                                            count++;
                                            if (data[6] instanceof String && data[6].toString().length() < 71) {
                                                count++;
                                                if (data[7] instanceof String && data[7].toString().length() < 31) {
                                                    count++;
                                                    if (data[8] instanceof String && data[8].toString().length() < 11) {
                                                        count++;
                                                        if (data[9].toString().matches("^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
                                                            count++;
                                                            if (data[10].toString().matches("^[+-]?\\d+(\\.\\d+)?$")) {
                                                                count++;
                                                                if (data[11] instanceof String && data[11].toString().length() < 41) {
                                                                    return true;
                                                                }
                                                            }
                                                        } else {
                                                            JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido\n Formato: YYYY-MM-DD");
                                                            return false;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                case "empleados":
                    if (data.length != 7) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1] instanceof String && data[1].toString().length() < 26) {
                            count++;
                            if (data[2] instanceof String && data[2].toString().length() < 26) {
                                count++;
                                if (data[3] instanceof String && data[3].toString().length() < 31) {
                                    count++;
                                    if (data[4] instanceof String && data[4].toString().length() < 71) {
                                        count++;
                                        if (data[5] instanceof String && data[5].toString().length() < 26) {
                                            count++;
                                            if (data[6].toString().matches("^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
                                                return true;
                                            } else {
                                                JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido\n Formato: YYYY-MM-DD");
                                                return false;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                case "rutas":
                    if (data.length != 5) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1] instanceof String && data[1].toString().length() < 26) {
                            count++;
                            if (data[2] instanceof String && data[2].toString().length() < 51) {
                                count++;
                                if (data[3].toString().matches("^[+-]?\\d+$")) {
                                    count++;
                                    if (data[4] instanceof String && data[4].toString().length() < 11) {
                                        return true;
                                    }
                                }
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                case "pedidos":
                    if (data.length != 10) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1].toString().matches("^[+-]?\\d+$")) {
                            count++;
                            if (data[2].toString().matches("^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])\\s(0\\d|1\\d|2[0-3]):[0-5]\\d:[0-5]\\d$")) {
                                count++;
                                if (data[3].toString().matches("^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
                                    count++;
                                    if (data[4] == null || data[4].toString().matches("^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
                                        count++;
                                        if (data[5].toString().matches("^[+-]?\\d+$")) {
                                            count++;
                                            if (data[6].toString().matches("^[+-]?\\d+$")) {
                                                count++;
                                                if (data[7] instanceof String && data[7].toString().length() < 26) {
                                                    count++;
                                                    if (data[8] == null || (data[8] instanceof String && data[8].toString().length() < 26)) {
                                                        count++;
                                                        if (data[9].toString().matches("^[+-]?\\d+(\\.\\d+)?$")) {
                                                            return true;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido\n Formato: YYYY-MM-DD");
                                        return false;
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido\n Formato: YYYY-MM-DD");
                                    return false;
                                }
                            } else {
                                JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido\n Formato: YYYY-MM-DD HH:MI:SS");
                                return false;
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                case "detalles_pedidos":
                    if (data.length != 7) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1].toString().matches("^[+-]?\\d+$")) {
                            count++;
                            if (data[2].toString().matches("^[+-]?\\d+$")) {
                                count++;
                                if (data[3].toString().matches("^[+-]?\\d+$")) {
                                    count++;
                                    if (data[4].toString().matches("^[+-]?\\d+(\\.\\d+)?$")) {
                                        count++;
                                        if (data[5].toString().matches("^[+-]?\\d+(\\.\\d+)?$")) {
                                            count++;
                                            if (data[6].toString().matches("^[+-]?\\d+(\\.\\d+)?$")) {
                                                return true;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                case "pagos":
                    if (data.length != 7) {
                        return false;
                    }
                    if (data[0].toString().matches("^[+-]?\\d+$")) {
                        count++;
                        if (data[1].toString().matches("^[+-]?\\d+$")) {
                            count++;
                            if (data[2].toString().matches("^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$")) {
                                count++;
                                if (data[3].toString().matches("^[+-]?\\d+(\\.\\d+)?$")) {
                                    count++;
                                    if (data[4] instanceof String && data[4].toString().length() < 31) {
                                        count++;
                                        if (data[5] instanceof String && data[5].toString().length() < 51) {
                                            count++;
                                            if (data[6] instanceof String && data[6].toString().length() < 31) {
                                                return true;
                                            }
                                        }
                                    }
                                }
                            } else {
                                JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido\n Formato: YYYY-MM-DD");
                                return false;
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(jdCreate, "Error en campo " + count + " validar valor introducido");
                    return false;

                default:
                    return false;
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            return false;
        }
    }

}
